apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql-oci
  namespace: mysql-ns
spec:
  releaseName: mysql-oci
  chart:
    spec:
      chart: mysql
      version: "14.0.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    auth:
      existingSecret: mysql-auth
    primary:
      persistence:
        enabled: false
      service:
        type: LoadBalancer
        loadBalancerIP: 172.31.15.241
