apiVersion: v1
kind: Secret
metadata:
    name: mysql-auth
    namespace: mysql
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:wqcXNw9VEGeI4K8UXq0lcw==,iv:t/C3KrcC2lyENK4TRulmrbSYPGCIfF9u7omSXEfx/kg=,tag:tRMHK69iGm9C0bjMIla+xQ==,type:str]
    mysql-password: ENC[AES256_GCM,data:yxRHDgnoT/JU7HITXzuC,iv:SowJOQsMLrLR0lVrgM5bvNxb5wZ8m17oDAeiBo1pHbg=,tag:CPRaS9ipeTDJsbL2YMv46g==,type:str]
sops:
    age:
        - recipient: age1c8vl3uef432ttk9j6nm9kl09xj9s6wz3hzu69jra7rwm733dvces4eqcgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb0JhaFkrK05HTmdGZWlD
            SERiQVlJd1lValI3bVhjQ0lRMHFzMEFuS2g0CmtUaG83VmxlSndwS0ZTWno1Nm80
            UkxOTmsyY200WDArL0ttdWc3aFRzbXMKLS0tIG1IekExTXpzSUVSZDBmS1RQTjQ3
            Y25raDg1Vm94T1FGYXgybElKR0pEdk0KLZiH9q4eTtDxJypJ4ZNdCtAQ6layggdO
            v46xZ85qHlDZcT5WFaaQBZs+WuRaE/oIbQfVQ4irAiyiJRwbt+2cvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T05:26:52Z"
    mac: ENC[AES256_GCM,data:2d23IBBO6dqeT2He0gRMl11YglguxfxGL4aJW+bzfcytddkKcj9wcTHBSagqOEtEoL3JDmgBloka5X2fSAv8RoFwZxcI2doE6E8RfrMOi2V5E5sY7uwsyEdwcuNhREK0mIA9eD2oHS2cuc5IABUNiqxF2pXbiVn7h3V3ha/7frs=,iv:U6iLUYB8REozDL1NhJSIxDHntTLpJVN5hvjEi/x5A5s=,tag:FwN9aPQHjn34F9Q37vnoQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
