apiVersion: v1
kind: Secret
metadata:
    name: mysql-auth
    namespace: mysql
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:X2KIvmJV094udug9AzHfTA==,iv:/ABZE3xcm24ounBkf4KffwVrdIfuj4MdlFGyMVOZQCk=,tag:jQOWFRB12PrH0F6wkwHEuA==,type:str]
    mysql-password: ENC[AES256_GCM,data:HOB1ISYrR+QpelIasIPy,iv:srZ5qnsSfx5CwEpFDFNjE25VJofLa54hhYStGg87KsE=,tag:8j/kuxpC96+llm+e4Lq8mg==,type:str]
sops:
    age:
        - recipient: age1fnck69dqhxlfgn3grsh7qlddzwrck08jry9heegeex5gljnvgeyqs7j78u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYnVhOUs0alBYNmx0MTFo
            aVVVcGVqRVgydEJqYUdRaUVYZXRuSnFiU1VNCnVvSTlBQ1pxNWZlZjNFNW5oTVh6
            SytadVoyZTdObWxZU1N0a05xbWwyRDAKLS0tIHUyRlB1OUN1M0JNcjJrR0RaYWtE
            WWpQV0xQaUNaMzhmUFhnb3RmVEt5L28KEuUnpp/jkyzlXrZWbBM16uamzfLSH67K
            ZOhOW+cvd92foW2iYMQ3RrbwutYbNmP40OjOsoBZHIKgjAIisfxEBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T06:32:55Z"
    mac: ENC[AES256_GCM,data:y3BgST7095DIN3bYdcInU0YWdkAcoPBD8mTOyID2QcI8jm77sqjwAvg2TmfoSGLXBGam9LyObVW41+Do0aaT8u4XDev07eSQ5woquPOqJCwLGt85ihd/sxDgo9pbRwVURHtkP/VqwncL/xiCr1BDbobam19glXamSj4VIM9ixvs=,iv:gVJL90bUjJ7lC83VATx1VEpl1yS69BeJYUSTvVgo8nA=,tag:95r4iArYGmISu6HD5v+5hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
