apiVersion: v1
kind: Secret
metadata:
    name: mysql-auth
    namespace: mysql
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:McJXpML0jBv3PFII5C5pQQ==,iv:KAfd7uxmtMx0iwm9KNyycK16hgC+WnYn8etHvYr+9YA=,tag:9tRMSnbUcGooAgquS7UNqg==,type:str]
    mysql-password: ENC[AES256_GCM,data:PYCjTWf4OCqsuAQZBrgBpQ==,iv:FqoaoH8DCqp97mfvbRU+yE+nBaZsD/TmvOaDivSm0w0=,tag:vEXmvazR+yVpCQiQZ5CBCw==,type:str]
sops:
    age:
        - recipient: age15grydf8mq27hxmdy0z78wk08ysxtptpfm2g3qazf32ycd7rsnyfqz7n2qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdE5aV1BnRThpSU1uNkU5
            VnB0RS9JM3lCd3lKSHNkd2RwbkE3RXJnTmdrCjBiNTdPL29mTnlIYmQyTWV0VGFu
            eHYzOGhBSGdwZGV3eTNkL3Jic0dMcHcKLS0tIGJ1dVBVamdrUlc4d3BsWTM5cWFo
            MVlGYTN2Y0RCSDVJNlllMnZIYk42N1kKLmbdov9Cy0YHe4kdQmyb+NP9Cmo/+7lG
            dqwGJ40N50x7r4BSxK1qC/I0eGqehqSZgo+8saFsGuarY2i+d0ourA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T10:02:35Z"
    mac: ENC[AES256_GCM,data:xnpqnxsos2Tdi7l9MRVONQLEPOrQgQJXag+iNKNmy8Jsw7ld7K+8eOZXrlDqeCtnlet7KcpmICZPKPcLZZs9i9YEeFZkuzSsB0zSkWYSooOwuqxjlhq6MNUfWhD3sMFJYsh8yBuWYD6DuhRSW9s6yvawxMmoAbxGIWDQVpnhsx4=,iv:awawb/UH0uOUddKOASFF1p+g9+4RLRZmplq7EdrrRfE=,tag:K0hmQU9y4/Q9puatzraZ9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
