apiVersion: v1
kind: Secret
metadata:
    name: mysql-auth
    namespace: mysql
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:0BWyQS74bxqjyvkzawcEcg==,iv:pzwLjOy/3CRpa0Y2WUa7lAoYjWNk2sltWzhBJgpwCt0=,tag:nVEMEE13gUz3JFTO0I6Cpw==,type:str]
    mysql-password: ENC[AES256_GCM,data:QoPfyie+lBCpeJQqd/u5,iv:IqOU0bbvUtOtJxe4IhXqiKQH/WzFDnM6wZUVu+G4J7E=,tag:yRVdlt1sQ5Ul8E23Dh+ukA==,type:str]
sops:
    age:
        - recipient: age1qk5c3j5gm92shvllepslu6z7f36d6rt7ad6rg43vrlkh23q3c5ls5800d7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTzBEV2laYjE0dllWMzFI
            OXBjSDIxWGtGelZhWnZtZzFBamlZNmJuTFFzCmJQNVJLY2R0NDNScmlCcWszcU41
            Qm9YSVBLSzl6ZkZ5LzV2ZEY1Rm9LVTQKLS0tIEF3c3hvZDZZM2RSTTNCWVJiVk9q
            WkFIeDJPSER3ZXNuT3NWY3QzanBHZUUK4TEgtX4WkFhI+kcdBhLe/NnwAT6cGpC4
            WzdVVgiI+5AyWbio1k4KKS97kreri2VgaU1OuOFrbar+KlM09Bar4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T06:15:27Z"
    mac: ENC[AES256_GCM,data:CP3XOSasDjuEjQrYyHwP8WJzqpggHx2sZelDRJZHS3yAc/FBQ3e/uxyRbX7IUgYT1Q0b6dUeLkPM71wuq7mRquv3iY7FVCCJTQaGzD9VZMXXSzyL72SekWGsMIzE0Voz+BJgu79Y11CF0ghsoRVdrPIWHzU0jjm1UsbB0aiCAxo=,iv:tLS2yhRUqlSFAnWmro20WBkUHJrF3Y3pfCviZ6UGsQ8=,tag:ULazCvWE6/tB6GPqVezbuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
