apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
name: metallb-upstream
namespace: flux-system
spec:
interval: 5m
sourceRef:
kind: GitRepository
name: metallb-source
path: "./config/manifests"
prune: true
targetNamespace: metallb-system
validation: client
wait: true