apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
name: metallb-config
namespace: flux-system
spec:
interval: 1m
sourceRef:
kind: GitRepository
name: flux-system
path: "./cluster/metallb"
prune: true
validation: client
wait: true