apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
name: metallb-ip-pool
namespace: metallb-system
spec:
addresses:
- 10.0.1.240/32 # <- REPLACE this: pick an IP or CIDR that works for your network (see README notes)
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
name: metallb-l2-advert
namespace: metallb-system
spec:
ipAddressPools:
- metallb-ip-pool